name: Expo Publish
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
      - run: yarn install
      - run: expo login -u $USERNAME -p $PASSWORD
      - env:        
          USERNAME: ${{ secrets.EXPO_CLI_USERNAME }}
          PASSWORD: ${{ secrets.EXPO_CLI_PASSWORD }}
      - run: expo publish
